create table enterprises (id bigint generated by default as identity, membership_date timestamp(6), company_name varchar(255), cuit varchar(255), primary key (id));

create table enterprise_transfer_info (amount numeric(38,2), id_enterprise bigint, id_transfer bigint not null, transaction_date timestamp(6), credit_account varchar(255), debit_account varchar(255), primary key (id_transfer));

    INSERT INTO Enterprises (id, cuit, companyName, membershipDate) VALUES
(1, '3012345698701', 'Coca', '2023-10-19T15:30:45.123');

INSERT INTO Enterprises (id, cuit, companyName, membershipDate) VALUES
(2, '3012345698401', 'Power',  '2023-10-19T15:30:46.123');

INSERT INTO Enterprises (id, cuit, companyName, membershipDate) VALUES
(3, '3012345698201', 'Dia',  '2023-10-19T15:30:47.123');

INSERT INTO Enterprises (id, cuit, companyName, membershipDate) VALUES
(4, '3012345698101', 'Sonic',  '2023-10-19T15:30:48.123');

INSERT INTO EnterpriseTransferInfo (idTransfer, amount, idEnterprise, debitAccount, creditAccount, transactionDate) VALUES
    (5, '20000', '1',  '1255544468988774658715', '1655544468988774658714','2023-10-19T16:32:45.123');

INSERT INTO EnterpriseTransferInfo (idTransfer, amount, idEnterprise, debitAccount, creditAccount, transactionDate) VALUES
    (6, '21000', '1',  '1255544468988774658715', '1555544468988774658715','2023-10-19T16:33:46.123');

INSERT INTO EnterpriseTransferInfo (idTransfer, amount, idEnterprise, debitAccount, creditAccount, transactionDate) VALUES
    (7, '22000', '1',  '1255544468988774658715', '1455544468988774658717','2023-10-19T16:34:47.123');

INSERT INTO EnterpriseTransferInfo (idTransfer, amount, idEnterprise, debitAccount, creditAccount, transactionDate) VALUES
    (8, '26000', '1',  '1255544468988774658715', '1855544468988774658718','2023-10-19T16:35:49.123');

INSERT INTO EnterpriseTransferInfo (idTransfer, amount, idEnterprise, debitAccount, creditAccount, transactionDate) VALUES
    (9, '46000', '3',  '1555544468988774658715', '1955544468988774658718','2023-10-19T16:35:49.123');